version: "3"
services:
  school_power_api:
    container_name: school_power_api
    image: "node:17.4.0-slim"
    expose:
      - "3000"
    volumes:
      - "./api:/home/school_power_api"
    working_dir: "/home/school_power_api"
    command: /bin/bash -c "ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && npm install && npm run start"
    environment:
      SP_PORT: 3000
      SP_DB_HOST: "school_power_db"
      SP_DB_PORT: 3306
      SP_DB_USER: "root"
      SP_DB_PASS: "123456"
      SP_DB_NAME: "school_power"
    restart: unless-stopped
  school_power_db:
    container_name: school_power_db
    image: "mariadb:10.5.3"
    expose:
      - "3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: "Asia/Shanghai"
    restart: unless-stopped
  school_power_crawler:
    container_name: school_power_crawler
    image: "python:3.9.10-slim"
    volumes:
      - "./crawler:/home/school_power_crawler"
    working_dir: "/home/school_power_crawler"
    command: /bin/bash -c "ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && pip install --no-cache-dir -r requirements.txt && python main.py"
    environment:
      SP_HOST: "https://dk.nynu.edu.cn"
      SP_SCHOOL_ID: 4
      SP_AES_KEY: "31323334353637383930414243444546"
      SP_USERNAME:
      SP_PASSWORD:
      SP_DB_HOST: "school_power_db"
      SP_DB_PORT: 3306
      SP_DB_USER: "root"
      SP_DB_PASS: "123456"
      SP_DB_NAME: "school_power"
    restart: unless-stopped
